first_proj/first_app/urls.py
from django.conf.urls import url
from first_app import views

app_name = "first_app"

urlpatterns = [
url(r'^users/$',views.users,name = "users"),
url(r'^forms/$',views.FormPage,name = "forms"),
url(r'^user_names/$',views.userNames,name = "usernames"),
url(r'^register/$',views.register,name = "register"),
url(r'^user_login/$',views.user_login,name = "user_login"),
url(r'^special/$',views.special,name = "special")
]

first_proj/first_proj/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from first_app import views
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index,name = "index"),
    url(r'^first_app/',include('first_app.urls')),
    url(r'^logout/',views.user_logout,name = "logout"),
]

first_proj/first_app/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Topic(models.Model):
    top_name = models.CharField(max_length = 100,unique = True)

    def __str__(self):
        return self.top_name

class WebPage(models.Model):
    topic = models.ForeignKey(Topic,on_delete=models.CASCADE)
    name = models.CharField(max_length = 100,unique = True)
    url = models.URLField(unique = True)

    def __str__(self):
        return self.name

class AccessRecord(models.Model):
    name = models.ForeignKey(WebPage,on_delete=models.CASCADE)
    date = models.DateField()

    def __str__(self):
        return str(self.date)

class Branch(models.Model):
    branch = models.CharField(max_length = 100,unique = True)

    def __str__(self):
        return self.branch

class StudentDetails(models.Model):
    branch = models.ForeignKey(Branch,on_delete = models.CASCADE)
    roll = models.CharField(max_length = 100, unique = True)
    name = models.CharField(max_length = 100, unique = True)
    def __str__(self):
        return self.roll

class StudentGrade(models.Model):
    roll = models.ForeignKey(StudentDetails,on_delete = models.CASCADE)
    grade = models.CharField(max_length = 100)
    result = models.CharField(max_length = 100)

    def __str__(self):
        return self.result

class LocUser(models.Model):
    firstName = models.CharField(max_length = 100)
    email = models.EmailField(max_length = 100)

    def __str__(self):
        return self.firstName

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    portfolio_site = models.URLField(blank = True)


    def __str__(self):
        return self.user.username

first_proj/first_app/forms.py
from django import forms
from django.contrib.auth.models import User
from first_app.models import LocUser,AccessRecord,UserProfileInfo
class FormName(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    text = forms.CharField(widget = forms.Textarea)

class NewUserForm(forms.ModelForm):
    passw = forms.CharField(widget = forms.PasswordInput)
    class Meta():
        model = LocUser
        fields = '__all__'

class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())
    class Meta():
        model = User
        fields = ("username","email","password")

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ("portfolio_site",)

first_proj/first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from first_app.models import Topic,WebPage,AccessRecord
from first_app.models import StudentGrade,StudentDetails,Branch,LocUser
from first_app import forms
from first_app.forms import NewUserForm,UserForm,UserProfileInfoForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login,logout

# Create your views here.
def index(request):
    WebPageList = WebPage.objects.order_by('topic')
    dateDict = {"accessRecords":WebPageList}
    studList = StudentGrade.objects.order_by('grade')
    studName = StudentDetails.objects.order_by('name')
    stuDict = {"studs":studList,
                "studNames": studName}
    return render(request,"first_app/index.html",context = stuDict)

def FormPage(request):
    form = forms.FormName()
    if request.method=='POST':
        form = forms.FormName(request.POST)
        if form.is_valid():
            print("Validation Success!")
            print("Name-"+form.cleaned_data['name'])
            print("Email-"+form.cleaned_data['email'])
            print("Text-"+form.cleaned_data['text'])
    return render(request,"first_app/formPage.html",{"form":form})

def users(request):
    form = NewUserForm()
    if request.method == 'POST':
        form = NewUserForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print("Invalid")
            return index(request)
    return render(request,"first_app/users.html",{"form":form})

def userNames(request):
    userList = LocUser.objects.order_by('firstName')
    userDict = {'users':userList}
    return render(request,"first_app/user_names.html",context = userDict)

def register(request):
    registered = False
    if request.method=="POST":
        user_form = UserForm(data = request.POST)
        profile_form = UserProfileInfoForm(data = request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit = False)
            profile.user = user
            profile.save()

            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,"first_app/register.html",
    {"user_form":user_form,
    "profile_form": profile_form,
    "registered":registered})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def special(request):
    return HttpResponse("Welcom to Special Page")

def user_login(request):
    if request.method=="POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username = username,password = password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Not active")
        else:
            print("Wrong")
            return HttpResponse("Inavlid credentials")
    else:
        return render(request,"first_app/login.html",{})

first_proj/templates/first_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>first_proj</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    {% block styles %}
    {% endblock %}

  </head>
  <body>

      <nav class="navbar navbar-expand-lg navbar-light default navbar-static-top" style="background-color: #e3f2fd;">
        <div class="container">
        <ul class="nav navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'index' %}">Home </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'first_app:users' %}">signUp</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'first_app:forms' %}">Form</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'first_app:register' %}">Register</a>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'first_app:special' %}">special</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'first_app:user_login' %}">Log In</a>
      </li>
      {% endif %}

      </ul>
          </div>
      </nav>

    {% block body_block %}
    {% endblock %}
  </body>
</html>

first_proj/templates/first_app/formPage.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
{% block body_block %}
      <div class="jumbotron">
          <h1>Form Page</h1>
      </div>
      <form method="POST">
        {{form.as_p}}
        {% csrf_token %}
        <input type="submit" name="submit" value="submit">
      </form>
      <a href="{% url 'index' %}">Click here to Go Home</a>
{% endblock %}

first_proj/templates/first_app/index.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
{% block body_block %}
      <div class="jumbotron">
        <h1>Go to /users page to signUp</h1>
        <a href="{% url 'first_app:users' %}">or Just click Here to register</a><br>
        <a href="{% url 'first_app:forms' %}">go to forms</a><br>
        <a href="{% url 'first_app:usernames' %}">Click here to display list of registered users</a>
      </div>
{% endblock %}

first_proj/templates/first_app/login.html
{% extends "first_app/base.html" %}
{% block body_block %}
<div class="jumbotron">
  <h1>Please login</h1>
  <form action="{% url 'first_app:user_login' %}" method="POST">
    {% csrf_token %}
    <label for="username">USER NAME</label>
    <input type="text" name="username">
    <label for="password">PASSWORD</label>
    <input type="password" name="password">
    <input type="submit" name="" value="submit">
  </form>
</div>
{% endblock %}

first_proj/templates/first_app/register.html
{% extends "first_app/base.html" %}
{% block body_block %}
<div class="jumbotron">
  {% if registered %}
  <h1>Thank You For Registering </h1>
  {% else %}
  <h1>Please register here</h1>
  <form method="POST">
    {% csrf_token %}
    {{user_form.as_p}}
    {{profile_form.as_p}}
    <input type="submit" name="" value="register">
  </form>
  {% endif %}

</div>
{% endblock %}

first_proj/templates/first_app/user_names.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/myFile.css' %}">
{% endblock %}
{% block body_block %}


<h1>Here are names of Registered users, Check if you are one of Us.</h1>

{% if users %}
<table>
  <tr>
    <th><u>User Names</u></th>
  </tr>
  {% for ent in users %}
  <tr>
    <td>{{ent.firstName|title}}</td>
  </tr>
  {% endfor %}
</table>
{% endif %}
<a href="{% url 'index' %}">Click here to go Home</a>
{% endblock %}

first_proj/templates/first_app/users.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
{% block body_block %}
      <div class="jumbotron">
        <h1>Please sign up</h1>
        <form method="POST">
          {{form.as_p}}
          {% csrf_token %}
          <input type="submit" name="submit" value="submit">
        </form>
        <a href="{% url 'index' %}">Click here to go home</a>
      </div>
{% endblock %}